/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccountDetails
 */
export interface CreateAccountDetails {
    /**
     * 
     * @type {string}
     * @memberof CreateAccountDetails
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAccountDetails
     */
    password: string;
    /**
     * 
     * @type {number}
     * @memberof CreateAccountDetails
     */
    permissions: number;
}

/**
 * Check if a given object implements the CreateAccountDetails interface.
 */
export function instanceOfCreateAccountDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "permissions" in value;

    return isInstance;
}

export function CreateAccountDetailsFromJSON(json: any): CreateAccountDetails {
    return CreateAccountDetailsFromJSONTyped(json, false);
}

export function CreateAccountDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['Username'],
        'password': json['Password'],
        'permissions': json['permissions'],
    };
}

export function CreateAccountDetailsToJSON(value?: CreateAccountDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Username': value.username,
        'Password': value.password,
        'permissions': value.permissions,
    };
}

