/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResourceResult
 */
export interface CreateResourceResult {
    /**
     * 
     * @type {number}
     * @memberof CreateResourceResult
     */
    id: number;
}

/**
 * Check if a given object implements the CreateResourceResult interface.
 */
export function instanceOfCreateResourceResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CreateResourceResultFromJSON(json: any): CreateResourceResult {
    return CreateResourceResultFromJSONTyped(json, false);
}

export function CreateResourceResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResourceResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreateResourceResultToJSON(value?: CreateResourceResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

