/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginReturn
 */
export interface LoginReturn {
    /**
     * 
     * @type {string}
     * @memberof LoginReturn
     */
    token: string;
    /**
     * 
     * @type {number}
     * @memberof LoginReturn
     */
    usertype: number;
}

/**
 * Check if a given object implements the LoginReturn interface.
 */
export function instanceOfLoginReturn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "usertype" in value;

    return isInstance;
}

export function LoginReturnFromJSON(json: any): LoginReturn {
    return LoginReturnFromJSONTyped(json, false);
}

export function LoginReturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginReturn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'usertype': json['usertype'],
    };
}

export function LoginReturnToJSON(value?: LoginReturn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'usertype': value.usertype,
    };
}

