/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MandalInfo
 */
export interface MandalInfo {
    /**
     * 
     * @type {Array<string>}
     * @memberof MandalInfo
     */
    mandals: Array<string>;
}

/**
 * Check if a given object implements the MandalInfo interface.
 */
export function instanceOfMandalInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "mandals" in value;

    return isInstance;
}

export function MandalInfoFromJSON(json: any): MandalInfo {
    return MandalInfoFromJSONTyped(json, false);
}

export function MandalInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MandalInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mandals': json['mandals'],
    };
}

export function MandalInfoToJSON(value?: MandalInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mandals': value.mandals,
    };
}

