/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderInfo } from './OrderInfo';
import {
    OrderInfoFromJSON,
    OrderInfoFromJSONTyped,
    OrderInfoToJSON,
} from './OrderInfo';

/**
 * 
 * @export
 * @interface OrderBookResults
 */
export interface OrderBookResults {
    /**
     * 
     * @type {Array<OrderInfo>}
     * @memberof OrderBookResults
     */
    orders: Array<OrderInfo>;
}

/**
 * Check if a given object implements the OrderBookResults interface.
 */
export function instanceOfOrderBookResults(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orders" in value;

    return isInstance;
}

export function OrderBookResultsFromJSON(json: any): OrderBookResults {
    return OrderBookResultsFromJSONTyped(json, false);
}

export function OrderBookResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderBookResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orders': ((json['orders'] as Array<any>).map(OrderInfoFromJSON)),
    };
}

export function OrderBookResultsToJSON(value?: OrderBookResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orders': ((value.orders as Array<any>).map(OrderInfoToJSON)),
    };
}

