/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderInfo
 */
export interface OrderInfo {
    /**
     * 
     * @type {number}
     * @memberof OrderInfo
     */
    orderid: number;
    /**
     * 
     * @type {number}
     * @memberof OrderInfo
     */
    lessor: number;
    /**
     * 
     * @type {number}
     * @memberof OrderInfo
     */
    lessee: number;
    /**
     * 
     * @type {number}
     * @memberof OrderInfo
     */
    resource: number;
    /**
     * 
     * @type {Date}
     * @memberof OrderInfo
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrderInfo
     */
    endTime: Date;
    /**
     * 
     * @type {number}
     * @memberof OrderInfo
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof OrderInfo
     */
    orderStatus: number;
}

/**
 * Check if a given object implements the OrderInfo interface.
 */
export function instanceOfOrderInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orderid" in value;
    isInstance = isInstance && "lessor" in value;
    isInstance = isInstance && "lessee" in value;
    isInstance = isInstance && "resource" in value;
    isInstance = isInstance && "startTime" in value;
    isInstance = isInstance && "endTime" in value;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "orderStatus" in value;

    return isInstance;
}

export function OrderInfoFromJSON(json: any): OrderInfo {
    return OrderInfoFromJSONTyped(json, false);
}

export function OrderInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderid': json['orderid'],
        'lessor': json['lessor'],
        'lessee': json['lessee'],
        'resource': json['resource'],
        'startTime': (new Date(json['start_time'])),
        'endTime': (new Date(json['end_time'])),
        'quantity': json['quantity'],
        'orderStatus': json['order_status'],
    };
}

export function OrderInfoToJSON(value?: OrderInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderid': value.orderid,
        'lessor': value.lessor,
        'lessee': value.lessee,
        'resource': value.resource,
        'start_time': (value.startTime.toISOString()),
        'end_time': (value.endTime.toISOString()),
        'quantity': value.quantity,
        'order_status': value.orderStatus,
    };
}

