/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderAcceptInfo
 */
export interface OrderAcceptInfo {
    /**
     * 
     * @type {number}
     * @memberof OrderAcceptInfo
     */
    newStatus: number;
}

/**
 * Check if a given object implements the OrderAcceptInfo interface.
 */
export function instanceOfOrderAcceptInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "newStatus" in value;

    return isInstance;
}

export function OrderAcceptInfoFromJSON(json: any): OrderAcceptInfo {
    return OrderAcceptInfoFromJSONTyped(json, false);
}

export function OrderAcceptInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderAcceptInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'newStatus': json['new_status'],
    };
}

export function OrderAcceptInfoToJSON(value?: OrderAcceptInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'new_status': value.newStatus,
    };
}

