/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderCreateDetails
 */
export interface OrderCreateDetails {
    /**
     * 
     * @type {number}
     * @memberof OrderCreateDetails
     */
    resourceId: number;
    /**
     * 
     * @type {Date}
     * @memberof OrderCreateDetails
     */
    fromTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrderCreateDetails
     */
    toTime: Date;
    /**
     * 
     * @type {number}
     * @memberof OrderCreateDetails
     */
    quantity: number;
}

/**
 * Check if a given object implements the OrderCreateDetails interface.
 */
export function instanceOfOrderCreateDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "resourceId" in value;
    isInstance = isInstance && "fromTime" in value;
    isInstance = isInstance && "toTime" in value;
    isInstance = isInstance && "quantity" in value;

    return isInstance;
}

export function OrderCreateDetailsFromJSON(json: any): OrderCreateDetails {
    return OrderCreateDetailsFromJSONTyped(json, false);
}

export function OrderCreateDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderCreateDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resourceId': json['resource_id'],
        'fromTime': (new Date(json['from_time'])),
        'toTime': (new Date(json['to_time'])),
        'quantity': json['quantity'],
    };
}

export function OrderCreateDetailsToJSON(value?: OrderCreateDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resource_id': value.resourceId,
        'from_time': (value.fromTime.toISOString()),
        'to_time': (value.toTime.toISOString()),
        'quantity': value.quantity,
    };
}

