/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceGroupInfo } from './ResourceGroupInfo';
import {
    ResourceGroupInfoFromJSON,
    ResourceGroupInfoFromJSONTyped,
    ResourceGroupInfoToJSON,
} from './ResourceGroupInfo';

/**
 * 
 * @export
 * @interface ResourceGroupReturn
 */
export interface ResourceGroupReturn {
    /**
     * 
     * @type {Array<ResourceGroupInfo>}
     * @memberof ResourceGroupReturn
     */
    resourceGroups: Array<ResourceGroupInfo>;
}

/**
 * Check if a given object implements the ResourceGroupReturn interface.
 */
export function instanceOfResourceGroupReturn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "resourceGroups" in value;

    return isInstance;
}

export function ResourceGroupReturnFromJSON(json: any): ResourceGroupReturn {
    return ResourceGroupReturnFromJSONTyped(json, false);
}

export function ResourceGroupReturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceGroupReturn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resourceGroups': ((json['resource_groups'] as Array<any>).map(ResourceGroupInfoFromJSON)),
    };
}

export function ResourceGroupReturnToJSON(value?: ResourceGroupReturn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resource_groups': ((value.resourceGroups as Array<any>).map(ResourceGroupInfoToJSON)),
    };
}

