/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceGroupInfo
 */
export interface ResourceGroupInfo {
    /**
     * 
     * @type {string}
     * @memberof ResourceGroupInfo
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceGroupInfo
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceGroupInfo
     */
    unit: string;
}

/**
 * Check if a given object implements the ResourceGroupInfo interface.
 */
export function instanceOfResourceGroupInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "unit" in value;

    return isInstance;
}

export function ResourceGroupInfoFromJSON(json: any): ResourceGroupInfo {
    return ResourceGroupInfoFromJSONTyped(json, false);
}

export function ResourceGroupInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceGroupInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
        'unit': json['unit'],
    };
}

export function ResourceGroupInfoToJSON(value?: ResourceGroupInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'id': value.id,
        'unit': value.unit,
    };
}

