/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceCreateDetails
 */
export interface ResourceCreateDetails {
    /**
     * 
     * @type {number}
     * @memberof ResourceCreateDetails
     */
    resourceGroupId: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceCreateDetails
     */
    data: string;
}

/**
 * Check if a given object implements the ResourceCreateDetails interface.
 */
export function instanceOfResourceCreateDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "resourceGroupId" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ResourceCreateDetailsFromJSON(json: any): ResourceCreateDetails {
    return ResourceCreateDetailsFromJSONTyped(json, false);
}

export function ResourceCreateDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceCreateDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resourceGroupId': json['resource_group_id'],
        'data': json['data'],
    };
}

export function ResourceCreateDetailsToJSON(value?: ResourceCreateDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resource_group_id': value.resourceGroupId,
        'data': value.data,
    };
}

