/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchDetails
 */
export interface SearchDetails {
    /**
     * 
     * @type {Date}
     * @memberof SearchDetails
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof SearchDetails
     */
    endTime: Date;
    /**
     * 
     * @type {number}
     * @memberof SearchDetails
     */
    resourceType: number;
}

/**
 * Check if a given object implements the SearchDetails interface.
 */
export function instanceOfSearchDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "startTime" in value;
    isInstance = isInstance && "endTime" in value;
    isInstance = isInstance && "resourceType" in value;

    return isInstance;
}

export function SearchDetailsFromJSON(json: any): SearchDetails {
    return SearchDetailsFromJSONTyped(json, false);
}

export function SearchDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startTime': (new Date(json['start_time'])),
        'endTime': (new Date(json['end_time'])),
        'resourceType': json['resource_type'],
    };
}

export function SearchDetailsToJSON(value?: SearchDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start_time': (value.startTime.toISOString()),
        'end_time': (value.endTime.toISOString()),
        'resource_type': value.resourceType,
    };
}

